/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sean Thomas (https://sketchfab.com/foon.)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/commercial-fridge-2174e1e4f1f24f1a95aa110ee060f473
Title: Commercial Fridge
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const DrinksFridge = (props) => {
  const { nodes, materials } = useGLTF("/models/fridgeDrinks.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Glass_lambert3_0.geometry}
          material={materials.lambert3}
          position={[-13.17, 95.515, -42.521]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={107.833}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Glass1_lambert3_0.geometry}
          material={materials.lambert3}
          position={[19.901, 95.515, -42.358]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={107.833}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube15_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder5_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube10_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube13_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube17_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube23_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube18_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube9_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube5_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube8_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube1_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_lambert2_0.geometry}
          material={materials.lambert2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tray2_lambert2_0.geometry}
          material={materials.lambert2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder2_lambert2_0.geometry}
          material={materials.lambert2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder7_lambert2_0.geometry}
          material={materials.lambert2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tray3_lambert2_0.geometry}
          material={materials.lambert2}
          position={[0, 35.997, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tray4_lambert2_0.geometry}
          material={materials.lambert2}
          position={[0, -36.741, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder58_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, 147.872, 0]}
          scale={[1, 1.374, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube39_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -12.531, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube40_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, 12.966, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube38_lambert1_0.geometry}
          material={materials.lambert1}
          position={[6.578, 0, -21.02]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube41_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube42_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder61_lambert1_0.geometry}
          material={materials.lambert1}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/fridgeDrinks.glb");

export default DrinksFridge;
