/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Red Fox / nokillnando (https://sketchfab.com/nokillnando)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fridge-df9a8f7f4b5a4dd3b6bcad6a8bdc1ad2
Title: Fridge
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

const PinkFridge = (props) => {
  const { nodes, materials } = useGLTF("/models/pinkFridge.glb");

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-20.023, 52.122, 13.756]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_6.geometry}
              material={materials.FridgeInsidePanel}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_7.geometry}
              material={materials.FridgeInsideGlass}
            />
          </group>
          <group
            position={[0, 13.686, -11.762]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_8.geometry}
              material={materials.FridgeInsidePanel}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_9.geometry}
              material={materials.FridgeInsideGlass}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_20.geometry}
              material={materials.FridgeBody}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_21.geometry}
              material={materials.FridgeInside}
            />
          </group>
          <group position={[0, 33.119, -10.842]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_22.geometry}
              material={materials.FridgeInsideMetal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_23.geometry}
              material={materials.FridgeInsideMetalHooks}
            />
          </group>
          <group
            position={[20.023, 41.222, 14.475]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_25.geometry}
              material={materials.FridgeInsidePanel}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_26.geometry}
              material={materials.FridgeInsideGlass}
            />
          </group>
          <group
            position={[0, -5.215, -11.762]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_27.geometry}
              material={materials.FridgeInsidePanel}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_28.geometry}
              material={materials.FridgeInsideGlass}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_29.geometry}
              material={materials.FridgeInsideLight}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_30.geometry}
              material={materials.FridgeInsidePanel}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_31.geometry}
              material={materials.FridgePanelDisplay}
            />
          </group>
          <group
            position={[39.936, -64.486, 54.457]}
            rotation={[0, Math.PI / 2, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_33.geometry}
              material={materials.FridgeDoors}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_34.geometry}
              material={materials.FridgeHandles}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_35.geometry}
              material={materials.FridgeRubber}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_36.geometry}
              material={materials.FridgeInsidePanelDoor}
            />
          </group>
          <group
            position={[39.936, 25.514, 54.457]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_39.geometry}
              material={materials.FridgeDoors}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_40.geometry}
              material={materials.FridgeHandles}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_41.geometry}
              material={materials.FridgeRubber}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_42.geometry}
              material={materials.FridgeInsidePanelDoor}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.PlasticHolders}
            position={[35.301, 30.679, 74.441]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.PlasticHolders}
            position={[35.301, 60.225, 74.441]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.PlasticHolders}
            position={[35.301, 45.491, 114.559]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.FridgeInsidePanel}
            position={[39.936, 25.514, 54.457]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.FridgeDoorHolders}
            position={[39.936, -64.486, 54.457]}
            rotation={[0, Math.PI / 2, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials.FridgeDoorHolders}
            position={[39.936, 25.514, 54.457]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_10.geometry}
            material={materials.FridgeInsideBasket}
            position={[0, -85.766, 21.027]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_11.geometry}
            material={materials.FridgeRefrigeratorGrate}
            position={[0, -55.232, 13.464]}
            rotation={[0, Math.PI / 2, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_12.geometry}
            material={materials["ZenUV_Generic_Material.003"]}
            position={[32.112, 80.081, 114.651]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_13.geometry}
            material={materials.ClearPlastic}
            position={[32.752, 70.408, 114.651]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_14.geometry}
            material={materials.PlasticHolders}
            position={[32.752, 70.408, 114.651]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_15.geometry}
            material={materials.ClearPlastic}
            position={[-19.77, 42.348, 12.49]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_16.geometry}
            material={materials["ZenUV_Generic_Material.002"]}
            position={[38.083, 24.97, 95.596]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_17.geometry}
            material={materials.PlasticHolders}
            position={[35.301, 22.806, 114.559]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_18.geometry}
            material={materials.FridgeInsidePanel}
            position={[0, 74.781, -9.595]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_19.geometry}
            material={materials.FridgeInsidePanel}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_24.geometry}
            material={materials["ZenUV_Generic_Material.001"]}
            position={[0, 40.216, -8.263]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_32.geometry}
            material={materials.FridgeInside}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_37.geometry}
            material={materials.FridgeHinges}
            position={[40.399, -31.992, 54.222]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_38.geometry}
            material={materials.FridgeHinges}
            position={[-0.999, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/pinkFridge.glb");

export default PinkFridge;
