/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mohamed.amir94812 (https://sketchfab.com/mohamed.amir94812)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/smart-fridge-d2d06c12322948c980877bf81fe42745
Title: Smart fridge
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const RedFridge = (props) => {
  const { nodes, materials } = useGLTF("/models/redFridge.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-3.515, -1.077, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_3.geometry}
            material={materials.screen}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.fridge_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_5.geometry}
            material={materials["fridge_grey.001"]}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/redFridge.glb");

export default RedFridge;
