/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: bretzel44 (https://sketchfab.com/bretzel44)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/food-open-fridge-716430c038ec4166a6d921d64e0867c6
Title: Food Open Fridge
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const TableFridge = (props) => {
  const { nodes, materials } = useGLTF("/models/fridgeTable.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, Math.PI]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bac_body_mat_bac_0.geometry}
            material={materials.mat_bac}
            position={[0, 0, 0.458]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bac_bump_mat_bac_0.geometry}
            material={materials.mat_bac}
            position={[0, 0, 0.67]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bac_bar_mat_bac_0.geometry}
            material={materials.mat_bac}
            position={[0, 0, 0.458]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bac_freeze_mat_bac_0.geometry}
            material={materials.mat_bac}
            position={[0, 0, 0.458]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bac_glass_mat_bac_0.geometry}
            material={materials.mat_bac}
            position={[0, 0, 0.459]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bac_glass_jonc_mat_bac_0.geometry}
            material={materials.mat_bac}
            position={[0, 0, 0.458]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bac_pied_mat_bac_0.geometry}
            material={materials.mat_bac}
            position={[0, 0, 0.157]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bac_wheel001_mat_bac_0.geometry}
            material={materials.mat_bac}
            position={[-0.749, -0.328, 0.031]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bac_wheel002_mat_bac_0.geometry}
            material={materials.mat_bac}
            position={[0.759, -0.328, 0.031]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bac_wheel003_mat_bac_0.geometry}
            material={materials.mat_bac}
            position={[0.759, 0.385, 0.031]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bac_wheel004_mat_bac_0.geometry}
            material={materials.mat_bac}
            position={[-0.749, 0.385, 0.031]}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/fridgeTable.glb");

export default TableFridge;
