/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: bretzel44 (https://sketchfab.com/bretzel44)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/food-shop-showcase-9079bf17aacf4570a0c2b2587104c5ab
Title: Food shop showcase
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const TwoDoorsFridge = (props) => {
  const { nodes, materials } = useGLTF("/models/fridgeTwoDoors.glb");

  return (
    <group {...props} dispose={null}>
      <group position={[0, -2.171, 0.92]} rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group
            position={[0.002, 0.016, 0.005]}
            rotation={[0, 0, -Math.PI / 2]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.tall003_black_arma_0.geometry}
              material={materials.black_arma}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.tall003_blue_steal2_0.geometry}
              material={materials.blue_steal2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.tall003_white_metal_0.geometry}
              material={materials.white_metal}
            />
          </group>
          <group
            position={[0.002, 0.016, 0.005]}
            rotation={[0, 0, -Math.PI / 2]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.glass00_joint_0.geometry}
              material={materials.joint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.glass00_glass_vitre_0.geometry}
              material={materials.glass_vitre}
            />
          </group>
          <group position={[0, 0.016, 0.005]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.glass001_joint_0.geometry}
              material={materials.joint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.glass001_glass_vitre_0.geometry}
              material={materials.glass_vitre}
            />
          </group>
          <group
            position={[0.002, 0.016, 0.005]}
            rotation={[0, 0, -Math.PI / 2]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.neon00_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.neon00_emissive_0.geometry}
              material={materials.emissive}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.neon001_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.neon001_emissive_0.geometry}
              material={materials.emissive}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.neon002_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.neon002_emissive_0.geometry}
              material={materials.emissive}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.neon003_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.neon003_emissive_0.geometry}
              material={materials.emissive}
            />
          </group>
          <group
            position={[0.002, 0.016, 0.005]}
            rotation={[0, 0, -Math.PI / 2]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.equere00_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.equere007_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.equere006_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.equere005_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.equere004_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.etagere001_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.vitremini001_glass_0.geometry}
              material={materials.glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.equere008_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.equere009_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.equere010_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.equere011_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.etagere002_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.vitremini002_glass_0.geometry}
              material={materials.glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.equere001_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.equere002_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.equere003_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.etagere_misc_metal_0.geometry}
              material={materials.misc_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.vitremini_glass_0.geometry}
              material={materials.glass}
            />
          </group>
          <group position={[-0.027, 0.079, 0.534]} scale={[0.948, 1, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.PORTE_D01_joint_0.geometry}
              material={materials.joint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.PORTE_D01_glass_vitre_0.geometry}
              material={materials.glass_vitre}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.cadrebd002_noir_metal_0.geometry}
              material={materials.noir_metal}
              rotation={[0, 0, Math.PI / 2]}
              scale={[-0.446, 2.006, 1.06]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.poignebd002_silver_0.geometry}
              material={materials.silver}
              rotation={[0, 0, Math.PI / 2]}
              scale={[-0.446, 2.006, 1.06]}
            />
          </group>
          <group position={[1.479, 0.079, 0.534]} scale={[0.948, 1, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.PORTE_D02_joint_0.geometry}
              material={materials.joint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.PORTE_D02_glass_vitre_0.geometry}
              material={materials.glass_vitre}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.cadrebd003_noir_metal_0.geometry}
              material={materials.noir_metal}
              rotation={[0, 0, Math.PI / 2]}
              scale={[-0.446, 2.006, 1.06]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.poignebd003_silver_0.geometry}
              material={materials.silver}
              rotation={[0, 0, Math.PI / 2]}
              scale={[-0.446, 2.006, 1.06]}
            />
          </group>
          <group
            position={[-1.518, 0.081, 0.533]}
            rotation={[0, 0, Math.PI]}
            scale={[0.948, 1, 1]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.PORTE_G01_joint_0.geometry}
              material={materials.joint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.PORTE_G01_glass_vitre_0.geometry}
              material={materials.glass_vitre}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.cadrebd_noir_metal_0.geometry}
              material={materials.noir_metal}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.446, 2.006, 1.06]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.poignebd_silver_0.geometry}
              material={materials.silver}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.446, 2.006, 1.06]}
            />
          </group>
          <group
            position={[-0.015, 0.081, 0.533]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.446, 1.901, 1.06]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.PORTE_G02_silver_0.geometry}
              material={materials.silver}
            />
            <group
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.499, 2.242, 0.943]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.glass003_joint_0.geometry}
                material={materials.joint}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.glass003_glass_vitre_0.geometry}
                material={materials.glass_vitre}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.cadrebd001_noir_metal_0.geometry}
              material={materials.noir_metal}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.socle001_blue_steal_0.geometry}
            material={materials.blue_steal}
            position={[0.002, 0.016, 0.005]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.joint001_joint_0.geometry}
            material={materials.joint}
            position={[1.529, 0.47, 1.287]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[1, 0.295, 0.998]}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/fridgeTwoDoors.glb");

export default TwoDoorsFridge;
